POST http://localhost:3000/login
Content-Type: application/json

{
    "user": "admin",
    "password": "1234"
}

###
DELETE http://localhost:3000/login

###
GET http://localhost:3000/items

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/5ee49f6fabb4e163660c62e7

###
POST http://localhost:3000/users
Content-Type: application/json

{ "user":"user"}
