POST http://localhost:3000/login
Content-Type: application/json

{
    "user": "username",
    "password": "password"
}

###
DELETE http://localhost:3000/login

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/5edffe78958b7efce73f546f

###
POST http://localhost:3000/users
Content-Type: application/json

{ "user":"user"}
