POST http://localhost:3000/login
Content-Type: application/json

{
    "user": "admin",
    "pwd": "1234"
}

###
DELETE http://localhost:3000/login

###
GET http://localhost:3000/vt

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users?query={"read":true}&limit=2&offset=2

###
GET http://localhost:3000/users/5ee79603c6ceac6bacc70964

###
GET http://localhost:3000/items

###
GET http://localhost:3000/items?query={"name":"House"}

###
GET http://localhost:3000/items/5ee79603c6ceac6bacc70964


###
GET http://localhost:3000/items/5ee79604c6ceac6bacc7096a
          
###
POST http://localhost:3000/users
Content-Type: application/json

{"read":true}
